import { Inter } from 'next/font/google'
import './globals.css'
import {Header} from "@/app/Header";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Header/>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
